import { useEffect, useMemo, useState } from 'react';

type Mission={title:string;rule:string;targets:{label:string,value:number}[];goal:number;mode:'sum'|'exact'|'range'};
const missions:Mission[]=[
 {title:'Build the Feed',rule:'Catch ingredient cards whose gram values add to exactly 120 g. Going over costs a life.',targets:[{label:'Rice flour',value:25},{label:'Pure water',value:35},{label:'Rice flour',value:45},{label:'Pure water',value:55},{label:'Rice flour',value:60},{label:'Pure water',value:75}],goal:120,mode:'sum'},
 {title:'Hit the Ratio',rule:'Catch exactly 90 g total. Think before you move—the values are mixed and every extra gram matters.',targets:[{label:'Flour',value:20},{label:'Water',value:30},{label:'Flour',value:40},{label:'Water',value:50},{label:'Flour',value:60},{label:'Water',value:70}],goal:90,mode:'sum'},
 {title:'Scale Calibration',rule:'Catch only cards that read exactly 50 g. Wrong measurements cost a life.',targets:[{label:'Flour',value:45},{label:'Water',value:50},{label:'Starter',value:55},{label:'Flour',value:50},{label:'Water',value:60},{label:'Starter',value:50}],goal:50,mode:'exact'},
 {title:'Temperature Window',rule:'Catch readings from 72°F through 78°F inclusive. Outside the target range costs a life.',targets:[{label:'Temp',value:68},{label:'Temp',value:72},{label:'Temp',value:75},{label:'Temp',value:78},{label:'Temp',value:81},{label:'Temp',value:76}],goal:0,mode:'range'},
 {title:'Half-Batch Math',rule:'The full batch calls for 160 g. Catch cards until you have exactly half that amount.',targets:[{label:'Ingredient',value:15},{label:'Ingredient',value:20},{label:'Ingredient',value:25},{label:'Ingredient',value:30},{label:'Ingredient',value:35},{label:'Ingredient',value:45}],goal:80,mode:'sum'}
];
type Falling={label:string;value:number;x:number;y:number};
const random=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
function makeFalling(m:Mission):Falling{const t=random(m.targets);return{...t,x:12+Math.random()*76,y:-12}}
function BasketArt(){return <svg viewBox="0 0 180 100" aria-hidden="true"><path d="M27 42h126l-15 48H42z" fill="#b96f37" stroke="#6b3e24" strokeWidth="6"/><path d="M48 42c5-37 79-37 84 0" fill="none" stroke="#d89a58" strokeWidth="10"/><path d="m42 55 89 34m-64-36 68 25m-85 11 71-34m-48 34 62-30" stroke="#e3ad70" strokeWidth="5" opacity=".8"/></svg>}
export default function BasketDash({onEarn,onExit}:{onEarn:(coins:number)=>void;onExit:()=>void}){
 const[missionIndex,setMissionIndex]=useState(()=>Math.floor(Math.random()*missions.length));const mission=missions[missionIndex];
 const[started,setStarted]=useState(false),[done,setDone]=useState(false),[claimed,setClaimed]=useState(false),[basketX,setBasketX]=useState(50),[item,setItem]=useState<Falling>(()=>makeFalling(mission)),[score,setScore]=useState(0),[hearts,setHearts]=useState(3),[time,setTime]=useState(40),[total,setTotal]=useState(0),[message,setMessage]=useState('Read the mission before the first card drops.');
 const reward=useMemo(()=>Math.max(3,Math.min(10,3+score+hearts)),[score,hearts]);
 function move(dir:number){setBasketX(x=>Math.max(8,Math.min(92,x+dir*12)))}
 function isCorrectCatch(cur:Falling){if(mission.mode==='exact')return cur.value===mission.goal;if(mission.mode==='range')return cur.value>=72&&cur.value<=78;return total+cur.value<=mission.goal}
 function resolve(cur:Falling,caught:boolean){if(mission.mode==='sum'){
   if(caught){const next=total+cur.value;if(next===mission.goal){setTotal(next);setScore(s=>s+3);setMessage(`Perfect total: ${next} g! Mission solved.`);setDone(true);return}if(next<mission.goal){setTotal(next);setScore(s=>s+1);setMessage(`Added ${cur.value} g. Running total: ${next}/${mission.goal} g.`)}else{setHearts(h=>Math.max(0,h-1));setMessage(`${cur.value} g would push you over ${mission.goal} g. Life lost.`)}}else setMessage(`Skipped ${cur.value} g. Total stays ${total}/${mission.goal} g.`)
 }else{
   const correct=isCorrectCatch(cur);if(caught&&correct){setScore(s=>s+1);setMessage(`Correct catch: ${cur.value}${mission.mode==='range'?'°F':' g'}.`)}else if(caught&&!correct){setHearts(h=>Math.max(0,h-1));setMessage(`Wrong catch: ${cur.value}${mission.mode==='range'?'°F':' g'}. Life lost.`)}else if(!caught&&correct){setHearts(h=>Math.max(0,h-1));setMessage(`Missed a valid ${cur.value}${mission.mode==='range'?'°F':' g'} card.`)}else{setScore(s=>s+1);setMessage(`Smart skip: ${cur.value}${mission.mode==='range'?'°F':' g'} did not fit the mission.`)}
 }
 setItem(makeFalling(mission))}
 useEffect(()=>{if(!started||done)return;const tick=window.setInterval(()=>setTime(t=>t<=1?0:t-1),1000);return()=>clearInterval(tick)},[started,done]);
 useEffect(()=>{if(started&&!done&&(time<=0||hearts<=0))setDone(true)},[time,hearts,started,done]);
 useEffect(()=>{if(!started||done)return;const fall=window.setInterval(()=>setItem(cur=>{const next={...cur,y:cur.y+4.2};if(next.y>=76){const caught=Math.abs(next.x-basketX)<14;window.setTimeout(()=>resolve(next,caught),0);return{...next,y:-30}}return next}),90);return()=>clearInterval(fall)},[started,done,basketX,total,missionIndex]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 function restart(){const next=Math.floor(Math.random()*missions.length);setMissionIndex(next);const m=missions[next];setStarted(false);setDone(false);setClaimed(false);setBasketX(50);setItem(makeFalling(m));setScore(0);setHearts(3);setTime(40);setTotal(0);setMessage('Read the new mission before the first card drops.')}
 return <section className="arcade-game">
  {!started&&!done&&<div className="arcade-start"><div className="arcade-logo"><span className="mini-bunny">🐇</span><div><small>QUEST MEADOW ARCADE · AGES 10–12</small><h2>BASKET DASH: QUICK CALCULATIONS</h2></div></div><div className="arcade-instructions"><div><b>1</b><span>{mission.title}</span><small>{mission.rule}</small></div><div><b>2</b><span>Calculate while cards fall</span><small>Catch or skip based on the numbers, not the picture.</small></div><div><b>3</b><span>Protect your three lives</span><small>Wrong decisions cost a life. Strong runs earn more coins.</small></div></div><button className="start-game" onClick={()=>setStarted(true)}>START 40-SECOND CHALLENGE →</button></div>}
  {started&&!done&&<><div className="arcade-hud"><span>⏱ {time}</span><span>⭐ {score}</span><span>❤ {hearts}</span>{mission.mode==='sum'&&<span>Σ {total}/{mission.goal} g</span>}</div><div className="arcade-field"><div className="distant-barn"/><div className="fence f1"/><div className="fence f2"/><div className="flower-row">✿　✼　✿　✼　✿　✼　✿</div><div className="falling-item" style={{left:`${item.x}%`,top:`${item.y}%`}}><div style={{fontSize:'2.2rem',fontWeight:900}}>⚖️</div><b>{item.label}</b><strong>{item.value}{mission.mode==='range'?'°F':' g'}</strong></div><div className="player-basket" style={{left:`${basketX}%`}}><BasketArt/></div><div className="arcade-message"><b>{mission.title}:</b> {mission.rule}<br/>{message}</div></div><div className="arcade-controls"><button onClick={()=>move(-1)}>◀ MOVE LEFT</button><button onClick={()=>move(1)}>MOVE RIGHT ▶</button></div></>}
  {done&&<div className="arcade-finish"><div className="finish-bunny">🐇</div><div><small>ROUND COMPLETE</small><h2>{score>=10?'Excellent mental math!':score>=6?'Strong calculation run!':'Keep sharpening the numbers!'}</h2><p>You scored <b>{score} points</b>{mission.mode==='sum'&&<> and finished at <b>{total}/{mission.goal} g</b></>}.</p><strong>Coin reward: 🪙 {reward}</strong>{!claimed?<button onClick={()=>{onEarn(reward);setClaimed(true)}}>COLLECT {reward} COINS</button>:<div className="finish-actions"><button onClick={restart}>NEW RANDOM MISSION</button><button onClick={onExit}>BACK TO GAME TRAIL</button></div>}</div></div>}
 </section>
}
