import { useEffect, useMemo, useState } from 'react';

type Bubble={id:number;x:number;y:number;size:number;speed:number;good:boolean;label:string};
const good=['Bubbles','Rise','Warmth','Tangy smell','Fermentation'];
const bad=['Soda','Candy','Chips','Freezer','Soap'];
function makeBubble(id:number):Bubble{const isGood=Math.random()>.35;const words=isGood?good:bad;return{id,x:8+Math.random()*82,y:82+Math.random()*25,size:54+Math.random()*28,speed:.8+Math.random()*1.2,good:isGood,label:words[Math.floor(Math.random()*words.length)]}}
export default function BubblePop({onEarn,onExit}:{onEarn:(n:number)=>void;onExit:()=>void}){
 const[started,setStarted]=useState(false),[done,setDone]=useState(false),[claimed,setClaimed]=useState(false);const[time,setTime]=useState(30),[score,setScore]=useState(0),[lives,setLives]=useState(3),[seq,setSeq]=useState(8);const[bubbles,setBubbles]=useState<Bubble[]>(()=>Array.from({length:8},(_,i)=>makeBubble(i)));
 const reward=useMemo(()=>Math.max(2,Math.min(8,2+Math.floor(score/4))),[score]);
 useEffect(()=>{if(!started||done)return;const t=window.setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[started,done]);
 useEffect(()=>{if(started&&(time===0||lives===0))setDone(true)},[started,time,lives]);
 useEffect(()=>{if(!started||done)return;const t=window.setInterval(()=>setBubbles(bs=>bs.map(b=>({...b,y:b.y-b.speed})).filter(b=>b.y>-16).concat(bs.filter(b=>b.y-b.speed<=-16).map(()=>makeBubble(seq+Math.floor(Math.random()*9999)))))),70);return()=>clearInterval(t)},[started,done,seq]);
 function pop(b:Bubble){setBubbles(bs=>bs.filter(x=>x.id!==b.id).concat(makeBubble(seq)));setSeq(s=>s+1);if(b.good)setScore(s=>s+2);else setLives(l=>Math.max(0,l-1))}
 function restart(){setStarted(false);setDone(false);setClaimed(false);setTime(30);setScore(0);setLives(3);setBubbles(Array.from({length:8},(_,i)=>makeBubble(i)))}
 return <section className="bubble-arcade">{!started&&!done?<div className="bubble-start"><div className="bubble-machine"><div className="glass">🫧</div><div className="machine-base">BUBBLE LAB</div></div><div><small>QUEST MEADOW GAME</small><h2>Bubble Pop</h2><p>Pop the <b>real fermentation clues</b> before they float away. Leave the silly bubbles alone.</p><p>Good clues give points. Pop three wrong bubbles and the round ends.</p><button onClick={()=>setStarted(true)}>START BUBBLE POP →</button></div></div>:started&&!done?<><div className="arcade-hud"><span>⏱ {time}</span><span>⭐ {score}</span><span>❤ {lives}</span></div><div className="bubble-playfield"><div className="bubble-lab-sign">FERMENTATION FIELD</div>{bubbles.map(b=><button key={b.id} className="floating-bubble" style={{left:`${b.x}%`,top:`${b.y}%`,width:b.size,height:b.size}} onClick={()=>pop(b)}><span>{b.label}</span></button>)}<div className="bubble-ground"><span>🐇</span><i>🌼　🌾　🌼　🌾</i></div></div></>:<div className="arcade-finish"><div className="finish-bunny">🐇</div><div><small>ROUND COMPLETE</small><h2>{score>=16?'Fermentation expert!':'Nice popping!'}</h2><p>You scored <b>{score}</b> by recognizing real starter clues.</p><strong>Coin reward: 🪙 {reward}</strong>{!claimed?<button onClick={()=>{onEarn(reward);setClaimed(true)}}>COLLECT {reward} COINS</button>:<div className="finish-actions"><button onClick={restart}>PLAY AGAIN</button><button onClick={onExit}>BACK TO GAME TRAIL</button></div>}</div></div>}</section>
}
