import { useEffect, useRef, useState } from 'react';
import './BunnyAdventure.css';

type Props={practiceMode?:boolean;onEarn:(n:number)=>void;onBack:()=>void;onGoStore:()=>void};
type Thing={id:number;kind:'coin'|'flour'|'water'|'jar'|'fox'|'coyote'|'eagle'|'log'|'hole';x:number;y:number};
const W=900,H=500,GROUND=405;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export default function BunnyAdventure({practiceMode=false,onEarn,onBack,onGoStore}:Props){
 const[x,setX]=useState(80),[y,setY]=useState(GROUND),[vy,setVy]=useState(0),[coins,setCoins]=useState(0),[supplies,setSupplies]=useState<string[]>([]),[hearts,setHearts]=useState(3),[won,setWon]=useState(false),[msg,setMsg]=useState('Run, jump, explore holes, dodge predators, and recover the starter supplies!');
 const keys=useRef<Record<string,boolean>>({});const id=useRef(100);const inv=useRef(0);const [things,setThings]=useState<Thing[]>(()=>[
  {id:1,kind:'coin',x:180,y:355},{id:2,kind:'log',x:250,y:385},{id:3,kind:'coin',x:315,y:330},{id:4,kind:'fox',x:390,y:385},{id:5,kind:'hole',x:485,y:397},{id:6,kind:'water',x:555,y:355},{id:7,kind:'coyote',x:650,y:385},{id:8,kind:'coin',x:720,y:330},{id:9,kind:'eagle',x:780,y:220},{id:10,kind:'jar',x:835,y:350}
 ]);
 function jump(){if(y>=GROUND-2)setVy(-13)}
 function hurt(name:string){if(Date.now()<inv.current)return;inv.current=Date.now()+1400;setHearts(h=>{const n=h-1;if(n<=0){setX(80);setY(GROUND);setMsg(`${name} caught Bunny! Back to the trailhead—but your recovered supplies are safe.`);return 3}return n});setMsg(`${name}! Dodge or jump next time. Energy -1.`)}
 function collect(t:Thing){if(t.kind==='coin'){setCoins(c=>c+1);setMsg('Bunnywood coin! Keep exploring.');setThings(a=>a.filter(q=>q.id!==t.id));return}if(['flour','water','jar'].includes(t.kind)){setSupplies(s=>s.includes(t.kind)?s:[...s,t.kind]);setThings(a=>a.filter(q=>q.id!==t.id));setMsg(`${t.kind==='flour'?'Brown rice flour':t.kind==='water'?'Filtered water':'Clear starter jar'} recovered!`);return}if(t.kind==='hole'){setMsg('Bunny drops into the burrow... there is something hidden below!');setThings(a=>a.filter(q=>q.id!==t.id).concat([{id:id.current++,kind:'flour',x:515,y:350},{id:id.current++,kind:'coin',x:535,y:320}]));return}if(t.kind==='fox')hurt('Fox');if(t.kind==='coyote')hurt('Coyote');if(t.kind==='eagle')hurt('Eagle')}
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if([' ','arrowup','w'].includes(e.key.toLowerCase()))jump()};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[y]);
 useEffect(()=>{if(won)return;const timer=window.setInterval(()=>{setX(px=>{let nx=px;if(keys.current['arrowleft']||keys.current['a'])nx-=6;if(keys.current['arrowright']||keys.current['d'])nx+=6;return clamp(nx,35,W-35)});setVy(v=>Math.min(14,v+0.7));setY(py=>{const ny=py+vy;return ny>=GROUND?GROUND:ny});setThings(ts=>ts.map(t=>t.kind==='fox'?{...t,x:clamp(t.x+(x>t.x?1.7:-1.7),25,W-25)}:t.kind==='coyote'?{...t,x:clamp(t.x+(x>t.x?2.4:-2.4),25,W-25)}:t.kind==='eagle'?{...t,x:clamp(t.x+(x>t.x?1.5:-1.5),25,W-25),y:220+Math.sin(Date.now()/250)*55}:t));},32);return()=>clearInterval(timer)},[vy,x,won]);
 useEffect(()=>{for(const t of things){const dx=Math.abs(x-t.x),dy=Math.abs(y-t.y);if(dx<34&&dy<48){if(t.kind==='log'){if(y>GROUND-35)hurt('Ouch—fallen log');continue}collect(t)}}},[x,y,things]);
 useEffect(()=>{if(supplies.includes('flour')&&supplies.includes('water')&&supplies.includes('jar')&&coins>=3&&!won){setWon(true);if(!practiceMode)onEarn(coins);setMsg('SUPPLY RUN COMPLETE! Bunny recovered the starter essentials and brought the coins home.')}},[supplies,coins,won]);
 const icon=(k:Thing['kind'])=>({coin:'🪙',flour:'🌾',water:'💧',jar:'🫙',fox:'🦊',coyote:'🐺',eagle:'🦅',log:'🪵',hole:'🕳️'}[k]);
 return <section className="ba-shell"><header><button onClick={onBack}>← BUNNYWOOD</button><div><small>QUEST MEADOW · ACTION EXPEDITION</small><h1>The Starter Supply Run</h1></div><div className="ba-hud"><b>❤ {hearts}</b><b>🪙 {coins}</b><b>🎒 {supplies.length}/3</b></div></header><div className="ba-mission">Find <b>flour + filtered water + a clear jar + 3 coins</b>. Foxes and coyotes chase. Eagles dive. Holes may hide supplies.</div><div className="ba-world" style={{width:'100%',aspectRatio:`${W}/${H}`}}><div className="ba-sky"/><div className="ba-hills"/><div className="ba-ground"/>{things.map(t=><div key={t.id} className={`ba-thing ${t.kind}`} style={{left:`${t.x/W*100}%`,top:`${t.y/H*100}%`}}>{icon(t.kind)}</div>)}<div className="ba-bunny" style={{left:`${x/W*100}%`,top:`${(y-55)/H*100}%`}}><img src="./resources/bunny-explorer.png" alt="Bunny"/></div><div className="ba-message">{msg}</div></div><div className="ba-controls"><button onPointerDown={()=>keys.current['a']=true} onPointerUp={()=>keys.current['a']=false}>◀ RUN</button><button onClick={jump}>JUMP ↑</button><button onPointerDown={()=>keys.current['d']=true} onPointerUp={()=>keys.current['d']=false}>RUN ▶</button></div><div className="ba-pack"><span className={supplies.includes('flour')?'got':''}>🌾 FLOUR</span><span className={supplies.includes('water')?'got':''}>💧 FILTERED WATER</span><span className={supplies.includes('jar')?'got':''}>🫙 CLEAR JAR</span></div>{won&&<div className="ba-win"><h2>SUPPLY RUN COMPLETE!</h2><p>Bunny made it through the meadow with the starter essentials.</p><button onClick={onGoStore}>TAKE THE COINS & SUPPLIES TO BUNNYWOOD →</button></div>}</section>
}
