import { useEffect, useMemo, useRef, useState } from 'react';
import './BunnyAdventure.css';

type Props={practiceMode?:boolean;onEarn:(n:number)=>void;onBack:()=>void;onGoStore:()=>void};
type Scene='trail'|'creek'|'burrow'|'ridge'|'wagon';
type Kind='coin'|'flour'|'water'|'jar'|'fox'|'coyote'|'eagle'|'log'|'rock'|'burrow'|'spring'|'exit';
type Thing={id:string;kind:Kind;x:number;y:number;collected?:boolean};
const W=1500,H=720,GROUND=590;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const SCENE_NAMES:Record<Scene,string>={trail:'Pine Trail',creek:'Creek Crossing',burrow:'Hidden Burrow',ridge:'Eagle Ridge',wagon:'Old Wagon Road'};
const STARTS:Record<Scene,number>={trail:90,creek:90,burrow:90,ridge:90,wagon:90};
const sceneThings:Record<Scene,Thing[]>={
 trail:[{id:'t1',kind:'coin',x:245,y:510},{id:'t2',kind:'log',x:390,y:555},{id:'t3',kind:'coin',x:520,y:475},{id:'t4',kind:'fox',x:760,y:550},{id:'t5',kind:'rock',x:930,y:550},{id:'t6',kind:'coin',x:1080,y:500},{id:'t7',kind:'exit',x:1415,y:525}],
 creek:[{id:'c1',kind:'coin',x:210,y:500},{id:'c2',kind:'rock',x:350,y:545},{id:'c3',kind:'burrow',x:625,y:555},{id:'c4',kind:'coin',x:815,y:475},{id:'c5',kind:'fox',x:980,y:550},{id:'c6',kind:'coin',x:1190,y:490},{id:'c7',kind:'exit',x:1415,y:525}],
 burrow:[{id:'b1',kind:'coin',x:260,y:505},{id:'b2',kind:'rock',x:430,y:550},{id:'b3',kind:'flour',x:690,y:500},{id:'b4',kind:'coin',x:860,y:455},{id:'b5',kind:'jar',x:1080,y:500},{id:'b6',kind:'exit',x:1375,y:525}],
 ridge:[{id:'r1',kind:'coin',x:240,y:470},{id:'r2',kind:'eagle',x:510,y:230},{id:'r3',kind:'log',x:650,y:555},{id:'r4',kind:'spring',x:875,y:520},{id:'r5',kind:'coin',x:1040,y:475},{id:'r6',kind:'eagle',x:1190,y:200},{id:'r7',kind:'exit',x:1415,y:525}],
 wagon:[{id:'w1',kind:'coin',x:220,y:500},{id:'w2',kind:'coyote',x:470,y:550},{id:'w3',kind:'rock',x:690,y:550},{id:'w4',kind:'coin',x:860,y:465},{id:'w5',kind:'coyote',x:1080,y:550},{id:'w6',kind:'coin',x:1225,y:500},{id:'w7',kind:'exit',x:1415,y:525}]
};
function EnemyArt({kind}:{kind:'fox'|'coyote'|'eagle'}){if(kind==='eagle')return <svg viewBox="0 0 120 80"><path d="M9 42c24-3 33-22 50-25 17 3 27 22 52 25-20 4-29 0-42 14l-10 15-10-15C36 42 27 46 9 42Z" fill="#6a4525"/><path d="M50 30h19l-9 10Z" fill="#f1d066"/><circle cx="63" cy="31" r="2" fill="#111"/></svg>;return <svg viewBox="0 0 120 80"><path d="M20 54 33 31l15 9c13-9 31-8 46 2l15-10-5 24c-5 12-23 18-44 16-22 1-39-5-40-18Z" fill={kind==='fox'?'#d96c2d':'#8a7d69'}/><path d="m33 31 1-17 14 22m46 6 10-20 5 28" fill={kind==='fox'?'#bd4f1d':'#6e6355'}/><circle cx="75" cy="48" r="3" fill="#111"/><path d="M96 55q8 3 12 0" fill="none" stroke="#111" strokeWidth="3"/><path d="M24 58 9 64" stroke={kind==='fox'?'#d96c2d':'#8a7d69'} strokeWidth="11" strokeLinecap="round"/></svg>}
function ItemArt({kind}:{kind:Kind}){if(kind==='coin')return <span className="ba-coin-art">$</span>;if(kind==='flour')return <div className="ba-bag-art"><b>RICE</b><small>FLOUR</small></div>;if(kind==='water')return <div className="ba-water-art">FILTERED</div>;if(kind==='jar')return <div className="ba-jar-art"/>;if(kind==='burrow')return <div className="ba-hole-art"><span>ENTER</span></div>;if(kind==='spring')return <div className="ba-spring-art"><i/><i/><i/></div>;if(kind==='log')return <div className="ba-log-art"/>;if(kind==='rock')return <div className="ba-rock-art"/>;if(kind==='exit')return <div className="ba-sign-art">TRAIL →</div>;return null}
export default function BunnyAdventure({practiceMode=false,onEarn,onBack,onGoStore}:Props){
 const[scene,setScene]=useState<Scene>('trail'),[x,setX]=useState(STARTS.trail),[y,setY]=useState(GROUND),[vy,setVy]=useState(0),[coins,setCoins]=useState(0),[supplies,setSupplies]=useState<string[]>([]),[hearts,setHearts]=useState(3),[won,setWon]=useState(false),[msg,setMsg]=useState('Follow the trail. Coins buy the tools Bunny still needs in Bunnywood.'),[collected,setCollected]=useState<string[]>([]),[burrowReturn,setBurrowReturn]=useState<Scene>('creek');
 const keys=useRef<Record<string,boolean>>({}),inv=useRef(0),lastX=useRef(0);const camera=clamp(x-230,0,W-480);const things=useMemo(()=>sceneThings[scene].filter(t=>!collected.includes(t.id)),[scene,collected]);
 function jump(){if(y>=GROUND-3)setVy(-15)}
 function hurt(name:string){if(Date.now()<inv.current)return;inv.current=Date.now()+1300;setHearts(h=>{const n=h-1;if(n<=0){setMsg(`${name} got Bunny! She retreats to the start of ${SCENE_NAMES[scene]}, but keeps everything already collected.`);setX(STARTS[scene]);setY(GROUND);return 3}return n});setMsg(`${name}! Energy -1. Keep moving.`)}
 function pickUp(t:Thing){if(t.kind==='coin'){setCoins(c=>c+1);setCollected(c=>[...c,t.id]);setMsg('Coin collected. Save it for starter tools in Bunnywood.');return}if(t.kind==='flour'){setSupplies(s=>s.includes('flour')?s:[...s,'flour']);setCollected(c=>[...c,t.id]);setMsg('Brown rice flour recovered from the hidden burrow!');return}if(t.kind==='jar'){setSupplies(s=>s.includes('jar')?s:[...s,'jar']);setCollected(c=>[...c,t.id]);setMsg('Clear starter jar recovered!');return}if(t.kind==='spring'){setSupplies(s=>s.includes('water')?s:[...s,'water']);setCollected(c=>[...c,t.id]);setMsg('Filtered water filled at the mountain spring!');return}}
 function action(){const near=things.find(t=>Math.abs(t.x-x)<70);if(near?.kind==='burrow'){setBurrowReturn(scene);setScene('burrow');setX(STARTS.burrow);setY(GROUND);setMsg('Bunny crawls underground. Find what was hidden here!');return}if(scene==='burrow'&&x>1300){setScene(burrowReturn);setX(760);setY(GROUND);setMsg('Back above ground. Keep heading toward Eagle Ridge.');return}setMsg('Nothing to enter here. Keep exploring.')}
 function nextScene(){if(scene==='trail'){setScene('creek');setX(STARTS.creek);setMsg('Creek Crossing: jump the rocks and look for a hidden burrow.')}else if(scene==='creek'){setScene('ridge');setX(STARTS.ridge);setMsg('Eagle Ridge: watch the sky. Find the filtered-water spring.')}else if(scene==='ridge'){setScene('wagon');setX(STARTS.wagon);setMsg('Old Wagon Road: coyotes patrol the last stretch back to Bunnywood.')}else if(scene==='wagon'){const ready=supplies.includes('flour')&&supplies.includes('water')&&supplies.includes('jar')&&coins>=8;if(ready){setWon(true);if(!practiceMode)onEarn(coins);setMsg('EXPEDITION COMPLETE! Bunny made it back with the starter essentials and shopping money.')}else setMsg(`Not ready to go home yet. Need flour, filtered water, jar, and 8 coins. You have ${supplies.length}/3 supplies and ${coins}/8 coins.`)}}
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.current[k]=true;if([' ','arrowup','w'].includes(k))jump();if(['e','arrowdown','s'].includes(k))action()};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[y,x,scene,things,burrowReturn]);
 useEffect(()=>{if(won)return;const timer=window.setInterval(()=>{setX(px=>{lastX.current=px;let nx=px;if(keys.current['arrowleft']||keys.current['a'])nx-=6;if(keys.current['arrowright']||keys.current['d'])nx+=6;return clamp(nx,35,W-35)});setVy(v=>Math.min(16,v+0.8));setY(py=>Math.min(GROUND,py+vy));},30);return()=>clearInterval(timer)},[vy,won]);
 useEffect(()=>{for(const t of things){const dx=Math.abs(x-t.x),dy=Math.abs(y-t.y);if(dx<44&&dy<60){if(['coin','flour','jar','spring'].includes(t.kind)){pickUp(t);continue}if(t.kind==='log'&&y>GROUND-55){hurt('Fallen log');continue}if(t.kind==='rock'&&y>GROUND-48){hurt('Rock');continue}if(t.kind==='exit'){if(scene==='burrow')action();else nextScene();continue}if(t.kind==='fox')hurt('Fox');if(t.kind==='coyote')hurt('Coyote');if(t.kind==='eagle'&&y<GROUND-10)hurt('Eagle')}}},[x,y,things,scene]);
 const predators=things.filter(t=>['fox','coyote','eagle'].includes(t.kind));
 const predatorPos=(t:Thing)=>{if(t.kind==='eagle'){const dive=Math.abs(x-t.x)<240?Math.min(GROUND-120,230+Math.abs(x-t.x)*.65):210+Math.sin(Date.now()/300)*35;return{x:t.x+(x>t.x?1:-1)*Math.max(0,220-Math.abs(x-t.x))*.12,y:dive}}const chase=Math.abs(x-t.x)<360?(x>t.x?1:-1)*(t.kind==='coyote'?85:55):0;return{x:t.x+chase,y:t.y}};
 return <section className="ba-shell ba-mobile-first"><header className="ba-topbar"><button onClick={onBack}>←</button><div><small>{SCENE_NAMES[scene]}</small><b>Starter Supply Run</b></div><div className="ba-hud"><span>♥ {hearts}</span><span>🪙 {coins}</span><span>🎒 {supplies.length}/3</span></div></header><div className="ba-viewport"><div className={`ba-stage ba-${scene}`} style={{width:`${W}px`,height:`${H}px`,transform:`translateX(-${camera}px)`}}><div className="ba-layer far"/><div className="ba-layer mid"/><div className="ba-layer near"/><div className="ba-ground-strip"/>{scene==='creek'&&<><div className="ba-creek-water"/><div className="ba-plank-bridge"/></>}{scene==='burrow'&&<><div className="ba-burrow-roof"/><div className="ba-burrow-lamps"><i/><i/><i/></div></>}{scene==='ridge'&&<div className="ba-waterfall"/>}{scene==='wagon'&&<div className="ba-old-wagon"/>}{things.filter(t=>!['fox','coyote','eagle'].includes(t.kind)).map(t=><div key={t.id} className={`ba-object ${t.kind}`} style={{left:t.x,top:t.y}}><ItemArt kind={t.kind}/></div>)}{predators.map(t=>{const p=predatorPos(t);return <div key={t.id} className={`ba-predator ${t.kind}`} style={{left:p.x,top:p.y}}><EnemyArt kind={t.kind as 'fox'|'coyote'|'eagle'}/>{t.kind==='eagle'&&Math.abs(x-t.x)<250&&<span className="ba-warning">!</span>}</div>})}<div className="ba-player" style={{left:x,top:y-70}}><img src="./resources/bunny-explorer.png" alt="Bunny"/></div></div><div className="ba-mini-status"><span className={supplies.includes('flour')?'got':''}>FLOUR</span><span className={supplies.includes('water')?'got':''}>WATER</span><span className={supplies.includes('jar')?'got':''}>JAR</span></div><div className="ba-message">{msg}</div></div><div className="ba-touch"><div className="ba-pad"><button onPointerDown={()=>keys.current['a']=true} onPointerUp={()=>keys.current['a']=false} onPointerCancel={()=>keys.current['a']=false}>◀</button><button onPointerDown={()=>keys.current['d']=true} onPointerUp={()=>keys.current['d']=false} onPointerCancel={()=>keys.current['d']=false}>▶</button></div><div className="ba-actions"><button className="jump" onClick={jump}>JUMP</button><button className="action" onClick={action}>ENTER</button></div></div>{won&&<div className="ba-win"><small>QUEST COMPLETE</small><h2>Bunny made it back to Bunnywood!</h2><p>She recovered the starter essentials and earned <b>{coins} coins</b> toward the scale, whisk, spatula, thermometer, timer and starter marker.</p><button onClick={onGoStore}>GO SHOPPING IN BUNNYWOOD →</button></div>}</section>}
