import { useEffect, useMemo, useState } from 'react';
import './QuestMeadow.css';
type Props={practiceMode?:boolean;coins:number;goalName?:string;goalCost?:number;onEarn:(n:number)=>void;onBack:()=>void;onGoStore:()=>void};
type ItemId='cog'|'rope'|'planks'|'key'|'pin';type ClueId='tracks'|'feather'|'echo';type Puzzle='windmill'|'marsh'|null;
type Spot={id:string;x:number;y:number;name:string;item?:ItemId;clue?:ClueId;bonus?:number;message:string;requires?:ItemId[];needsClue?:ClueId;danger?:boolean};
const START={x:50,y:67};
const spots:Spot[]=[{id:'tracks',x:66,y:63,name:'Wagon Tracks',clue:'tracks',message:'These wheel ruts are deeper on one side. The wagon was dragging something heavy toward the lower trail.'},{id:'mill',x:24,y:31,name:'Windmill Mechanism',item:'cog',message:'A loose gear housing contains the missing GATE COG.'},{id:'marsh-crate',x:58,y:59,name:'Muddy Marsh',item:'rope',message:'Following the wagon evidence into the reeds, you find BRIDGE ROPE.',needsClue:'tracks'},{id:'woods-stack',x:52,y:29,name:'Whispering Woods',item:'planks',message:'Scrape marks lead to three straight BRIDGE PLANKS.',needsClue:'tracks'},{id:'bridge',x:40,y:43,name:'Broken Bridge',message:'You combine the recovered rope and planks to repair the crossing.',requires:['rope','planks']},{id:'feather',x:70,y:25,name:'Black Feather',clue:'feather',message:'A black feather has a brass-colored scratch. Something shiny was carried toward the upper trail.'},{id:'crow-tree',x:72,y:34,name:'Crow Hollow',item:'key',message:'The feather clue leads you to the WAGON KEY.',requires:['cog'],needsClue:'feather'},{id:'echo-mark',x:35,y:60,name:'Scratched Stone',clue:'echo',message:'A wheel-shaped scratch points toward Echo Cave. A metallic tapping repeats from inside.'},{id:'cave',x:20,y:57,name:'Echo Cave',item:'pin',message:'You follow the echo and recover the missing WHEEL PIN.',requires:['rope','planks'],needsClue:'echo'},{id:'cache1',x:15,y:39,name:'Loose Flat Rock',bonus:3,message:'Secret cache! Three Bunnywood coins are hidden under the rock.'},{id:'cache2',x:77,y:70,name:'Hollow Log',bonus:2,message:'Secret cache! Two Bunnywood coins are tucked inside the hollow log.'},{id:'berries',x:31,y:50,name:'Berry Patch',message:'Only berries. Bunny loses energy checking the wrong place.',danger:true},{id:'stump',x:63,y:39,name:'Rotten Stump',message:'Beetles burst from the stump. Bunny loses energy.',danger:true},{id:'pond',x:51,y:57,name:'Deep Marsh Edge',message:'The bank gives way. Bunny scrambles back and loses energy.',danger:true},{id:'wagon',x:76,y:38,name:'Lost Supply Wagon',message:'The key turns and the wheel pin fits. The Lost Supply Wagon is ready to return to Bunnywood!',requires:['cog','rope','planks','key','pin']}];
const itemNames:Record<ItemId,string>={cog:'Gate Cog',rope:'Bridge Rope',planks:'Bridge Planks',key:'Wagon Key',pin:'Wheel Pin'};const clueNames:Record<ClueId,string>={tracks:'Wagon Trail Evidence',feather:'Crow Evidence',echo:'Echo Cave Evidence'};
const marshValues=[34,7,21,11,6,13,4,8,3,9,5,17,2,12,19,10];
const marshPath=[12,8,10,7,5,2,0];
export default function QuestMeadow({practiceMode=false,coins,goalName,goalCost,onEarn,onBack,onGoStore}:Props){const[pos,setPos]=useState(START);const[inventory,setInventory]=useState<ItemId[]>([]);const[clues,setClues]=useState<ClueId[]>([]);const[searched,setSearched]=useState<string[]>([]);const[hearts,setHearts]=useState(3);const[bonus,setBonus]=useState(0);const[feedback,setFeedback]=useState('');const[complete,setComplete]=useState(false);const[rewarded,setRewarded]=useState(false);const[journalOpen,setJournalOpen]=useState(false);const[puzzle,setPuzzle]=useState<Puzzle>(null);const[gears,setGears]=useState([0,0,0]);const[gearMoves,setGearMoves]=useState(0);const[marshSteps,setMarshSteps]=useState<number[]>([]);const missing=Math.max(0,(goalCost||0)-coins);const goalReady=!!goalName&&!!goalCost&&missing===0;const near=useMemo(()=>spots.find(s=>Math.hypot(pos.x-s.x,pos.y-s.y)<7),[pos]);const baseReward=Math.max(6,Math.min(10,missing||8));
 function tell(text:string){setFeedback(text);window.setTimeout(()=>setFeedback(''),2400)}
 function move(dx:number,dy:number){if(complete||puzzle)return;setPos(p=>({x:Math.max(10,Math.min(88,p.x+dx)),y:Math.max(20,Math.min(72,p.y+dy))}))}
 function finishSpot(s:Spot){setSearched(v=>v.includes(s.id)?v:[...v,s.id]);if(s.clue&&!clues.includes(s.clue))setClues(v=>[...v,s.clue!]);if(s.item&&!inventory.includes(s.item))setInventory(v=>[...v,s.item!]);if(s.id==='wagon')setComplete(true);tell(s.message)}
 function search(s:Spot){if(searched.includes(s.id))return;if(s.requires&&!s.requires.every(x=>inventory.includes(x))){const have=s.id==='wagon'?inventory.length:0;tell(s.id==='wagon'?`The wagon cannot move yet. Repair items found: ${have}/5. Keep exploring the Meadow.`:'This location is locked by the quest. Keep exploring for the missing clue or repair item.');return}if(s.needsClue&&!clues.includes(s.needsClue)){tell('Bunny needs more evidence before she can solve this location. Keep exploring.');return}if(s.id==='mill'){setPuzzle('windmill');setGears([0,0,0]);setGearMoves(0);return}if(s.id==='marsh-crate'){setPuzzle('marsh');setMarshSteps([]);return}if(s.danger){setSearched(v=>[...v,s.id]);setHearts(h=>Math.max(1,h-1));tell(`${s.message} ❤️ -1`);return}if(s.bonus){setSearched(v=>[...v,s.id]);setBonus(v=>v+s.bonus!);tell(`${s.message} +${s.bonus}`);return}finishSpot(s)}
 function rotateGear(i:number){if(gearMoves>=9)return;setGears(g=>g.map((v,n)=>n===i?(v+1)%4:v));setGearMoves(m=>m+1)}
 function testGears(){if(gears[0]===1&&gears[1]===3&&gears[2]===2){setPuzzle(null);finishSpot(spots.find(s=>s.id==='mill')!)}else{setHearts(h=>Math.max(1,h-1));setGears([0,0,0]);setGearMoves(0);tell('The gears grind and reset. Study the carved arrows more carefully. Energy -1.')}}
 function stepMarsh(i:number){const expected=marshPath[marshSteps.length];if(i===expected){const next=[...marshSteps,i];setMarshSteps(next);if(next.length===marshPath.length){setPuzzle(null);finishSpot(spots.find(s=>s.id==='marsh-crate')!)}}else{setHearts(h=>Math.max(1,h-1));setMarshSteps([]);tell('SPLASH! Wrong deduction. The safe trail disappears and Bunny must start from the bank. Energy -1.')}}
 useEffect(()=>{if(puzzle||complete)return;const arrived=spots.find(s=>!searched.includes(s.id)&&Math.hypot(pos.x-s.x,pos.y-s.y)<4.8);if(arrived)search(arrived)},[pos]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(puzzle)return;if(['ArrowLeft','a','A'].includes(e.key))move(-3,0);else if(['ArrowRight','d','D'].includes(e.key))move(3,0);else if(['ArrowUp','w','W'].includes(e.key))move(0,-3);else if(['ArrowDown','s','S'].includes(e.key))move(0,3)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 function claim(){if(rewarded||practiceMode)return;onEarn(baseReward+bonus);setRewarded(true)}function restart(){setPos(START);setInventory([]);setClues([]);setSearched([]);setHearts(3);setBonus(0);setComplete(false);setRewarded(false);setPuzzle(null);setMarshSteps([]);tell(practiceMode?'Practice expedition restarted.':'New expedition. Follow the evidence.')}
 return <section className="qm-shell qm-illustrated"><div className="qm-mobile-stage"><img className="qm-map-art" src="./resources/quest-meadow-mobile.png" alt="Quest Meadow adventure map"/><button className="qm-home-hit" onClick={onBack} aria-label="Return to Bunnywood"/><button className="qm-journal-hit" onClick={()=>setJournalOpen(true)} aria-label="Open journal"/><button className="qm-reset-hit" onClick={restart} aria-label="Reset map"/><button className="qm-look-hit" onClick={()=>near?search(near):tell('Nothing close enough to investigate. Keep moving Bunny around the Meadow.')} aria-label="Look nearby"/><button className="qm-up-hit" onClick={()=>move(0,-4)} aria-label="Move up"/><button className="qm-down-hit" onClick={()=>move(0,4)} aria-label="Move down"/><button className="qm-left-hit" onClick={()=>move(-4,0)} aria-label="Move left"/><button className="qm-right-hit" onClick={()=>move(4,0)} aria-label="Move right"/>{spots.map(s=><span key={s.id} className={`qm-art-hotspot ${searched.includes(s.id)?'searched':''}`} style={{left:`${s.x}%`,top:`${s.y}%`}} aria-hidden="true"/>)}<div className="qm-art-player" style={{left:`${pos.x}%`,top:`${pos.y}%`}}><img src="./resources/bunny-explorer.png" alt="Bunny"/></div>{practiceMode&&<div className="qm-practice-dot">P</div>}{feedback&&<div className="qm-feedback">{feedback}</div>}
 {puzzle==='windmill'&&<div className="qm-puzzle"><small>WINDMILL HILL</small><h2>Repair the Gear Lock</h2><p>The metal plate is carved with three clues: <b>Sunrise → Moon → Sunset</b>. Rotate the three gears so their pointers face <b>East, West, South</b>. You have 9 turns.</p><div className="qm-gears">{gears.map((g,i)=><button key={i} onClick={()=>rotateGear(i)} className="qm-gear" style={{transform:`rotate(${g*90}deg)`}}>▲<span>{i+1}</span></button>)}</div><div className="qm-puzzle-status">Turns: {gearMoves}/9 · Energy: {hearts}/3</div><button className="qm-test" onClick={testGears}>TEST MECHANISM</button><button className="qm-cancel" onClick={()=>setPuzzle(null)}>BACK TO MAP</button></div>}
 {puzzle==='marsh'&&<div className="qm-puzzle"><small>MUDDY MARSH</small><h2>Decode the Sinking-Stone Trail</h2><p>Bunny finds two numbers scratched into the bank: <b>2, 3</b>. A faded note says: <b>“After the first two, every safe stone carries the total of the previous two.”</b> The safe trail bends through the marsh, so you must find the connected route yourself. Decoy stones are mixed in. One wrong deduction sinks the trail and resets it.</p><div className="qm-stones">{marshValues.map((n,i)=><button key={i} className={marshSteps.includes(i)?'safe':''} onClick={()=>stepMarsh(i)}>{n}</button>)}</div><div className="qm-puzzle-status">Trail decoded: {marshSteps.length}/7 · Energy: {hearts}/3</div><button className="qm-cancel" onClick={()=>setPuzzle(null)}>BACK TO MAP</button></div>}
 {journalOpen&&<div className="qm-drawer"><button className="qm-close" onClick={()=>setJournalOpen(false)}>×</button><small>EXPEDITION JOURNAL</small><h2>Evidence</h2>{(['tracks','feather','echo'] as ClueId[]).map(c=><div key={c} className={clues.includes(c)?'done':''}><span>{clues.includes(c)?'✓':'?'}</span><b>{clues.includes(c)?clueNames[c]:'Undiscovered clue'}</b></div>)}<h2>Recovered Gear</h2>{(['cog','rope','planks','key','pin'] as ItemId[]).map(i=><div key={i} className={inventory.includes(i)?'done':''}><span>{inventory.includes(i)?'✓':'□'}</span><b>{inventory.includes(i)?itemNames[i]:'Unknown item'}</b></div>)}<p>Energy: <b>{hearts}/3</b> · Coins: <b>{coins}</b> · Bonus: <b>+{bonus}</b></p></div>}{complete&&<div className="qm-art-win"><small>EXPEDITION COMPLETE</small><h2>The Lost Supply Wagon is coming home!</h2>{practiceMode?<button onClick={restart}>PLAY AGAIN</button>:!rewarded?<button onClick={claim}>CLAIM {baseReward+bonus} COINS</button>:goalReady?<button onClick={onGoStore}>GO TO STORE</button>:<button onClick={restart}>NEW EXPEDITION</button>}</div>}</div></section>}
