import { useMemo, useState } from 'react';
import BasketDash from './BasketDash';
import BubblePop from './BubblePop';
import ToolTrail from './ToolTrail';
type Props={coins:number;goalName?:string;goalCost?:number;onEarn:(n:number)=>void;onBack:()=>void;onGoStore:()=>void};
type Game='menu'|'basket'|'bubbles'|'tools';
export default function QuestMeadow({coins,goalName,goalCost,onEarn,onBack,onGoStore}:Props){
 const[game,setGame]=useState<Game>('menu');const missing=Math.max(0,(goalCost||0)-coins);const goalReady=!!goalName&&!!goalCost&&missing===0;const meadowMessage=useMemo(()=>goalReady?`We have enough for ${goalName}!`:goalName?`We need ${missing} more coin${missing===1?'':'s'} for ${goalName}. Pick a game and earn them.`:'Pick a game, learn something useful, and earn coins.',[goalReady,goalName,missing]);const reset=()=>setGame('menu');
 return <section className="quest-place"><div className="quest-hero"><div className="quest-sky"><span className="cloud c1">☁️</span><span className="cloud c2">☁️</span><span className="sun">☀️</span></div><div className="quest-hills"/><div className="quest-grass"><i>🌼</i><i>🌸</i><i>🌻</i><i>🌷</i><i>🌼</i></div><div className="quest-sign">QUEST<br/>MEADOW</div><div className="quest-bunny">🐇</div><div className="quest-speech"><small>BUNNY'S COIN QUEST</small><h1>{meadowMessage}</h1><p>Quest Meadow is where we earn spending money before our bakery can support itself. Play well, learn real sourdough skills, then take the coins to the shops.</p><div className="quest-wallet"><span>🪙 {coins}</span>{goalName&&goalCost&&<span>{goalReady?'✓ READY TO BUY':`🎯 ${goalName}: ${goalCost}`}</span>}</div></div><button className="quest-back" onClick={onBack}>← TOWN</button></div>
 {game==='menu'&&<div className="quest-games"><button className="quest-game basket-game" onClick={()=>setGame('basket')}><div className="game-art"><span>🧺</span><i>🌾</i><b>💧</b></div><div><small>ARCADE CATCHING GAME</small><h2>Basket Dash</h2><p>Move the basket. Catch real starter supplies and dodge junk.</p><strong>Earn 2–8 coins</strong></div><em>PLAY →</em></button><button className="quest-game bubble-game" onClick={()=>setGame('bubbles')}><div className="game-art"><span>🫧</span><i>🫧</i><b>🫧</b></div><div><small>ARCADE POPPING GAME</small><h2>Bubble Pop</h2><p>Pop real fermentation clues as they float through the field.</p><strong>Earn 2–8 coins</strong></div><em>PLAY →</em></button><button className="quest-game match-game" onClick={()=>setGame('tools')}><div className="game-art"><span>🛤️</span><i>⚖️</i><b>🌡️</b></div><div><small>TRAIL ACTION GAME</small><h2>Tool Trail</h2><p>Guide bakery tools down the right trail to the job they perform.</p><strong>Earn 2–7 coins</strong></div><em>PLAY →</em></button>{goalReady&&<button className="quest-ready" onClick={onGoStore}>🛒 We earned enough! Go buy {goalName} →</button>}</div>}
 {game==='basket'&&<div className="quest-stage"><div className="quest-stage-bar"><button onClick={reset}>← GAME TRAIL</button><b>🧺 Basket Dash</b><span>🪙 {coins}</span></div><BasketDash onEarn={onEarn} onExit={reset}/></div>}
 {game==='bubbles'&&<div className="quest-stage"><div className="quest-stage-bar"><button onClick={reset}>← GAME TRAIL</button><b>🫧 Bubble Pop</b><span>🪙 {coins}</span></div><BubblePop onEarn={onEarn} onExit={reset}/></div>}
 {game==='tools'&&<div className="quest-stage"><div className="quest-stage-bar"><button onClick={reset}>← GAME TRAIL</button><b>🛤️ Tool Trail</b><span>🪙 {coins}</span></div><ToolTrail onEarn={onEarn} onExit={reset}/></div>}</section>
}
