import { useState } from 'react';
import { starterSupplies } from '../data/game';
type Props={completed:boolean;onComplete:()=>void;onBack:()=>void;onQuest:()=>void};
const stations=[
 {title:'Meet the Starter',prompt:'Investigate the jar. Find all three clues before Bunny moves on.',icon:'🫙',facts:['Flour is food for the culture.','Filtered water hydrates the flour.','Wild yeast and helpful bacteria make the culture alive.'],check:'A starter is not just flour paste. It is a living culture we feed and observe.'},
 {title:'Build the Starter Kit',prompt:'Inspect the workbench and discover why bakers use these tools.',icon:'⚖️',facts:['A gram scale makes measurements repeatable.','A clear jar lets us see bubbles and rise.','A thermometer helps explain fermentation speed.'],check:'Good tools let us measure what is happening instead of guessing.'},
 {title:'Read the Clues',prompt:'Study Bunny’s observation station before leaving for town.',icon:'🔎',facts:['Rise shows expansion.','Bubbles show gas production.','Aroma, time, and temperature add context.'],check:'A baker combines several clues before deciding what a starter needs.'}
];
export default function Schoolhouse({completed,onComplete,onBack,onQuest}:Props){
 const[station,setStation]=useState(0);const[revealed,setRevealed]=useState<number[]>([]);const[openItem,setOpenItem]=useState<string|null>(null);const s=stations[station];const ready=revealed.length===3;
 function reveal(i:number){setRevealed(v=>v.includes(i)?v:[...v,i])}function next(){if(station<2){setStation(x=>x+1);setRevealed([])}else onComplete()}
 return <section className="redesigned-school"><div className="school-world"><button className="school-back" onClick={onBack}>← BUNNYWOOD</button><div className="school-title"><small>BUNNYWOOD SCHOOLHOUSE</small><h1>Starter School</h1><p>{completed?'MISSION UNLOCKED':`DISCOVERY ${station+1} OF 3`}</p></div><div className="classroom-window"><span className="sun">☀</span><i className="hill-one"/><i className="hill-two"/></div><div className="chalkboard"><small>{completed?'STARTER APPRENTICE':s.title.toUpperCase()}</small><b>{completed?'LEARN ✓  →  EARN  →  SHOP  →  MAKE':s.prompt}</b><p>{completed?'Your first real adventure begins outside the Schoolhouse.':'Explore the room. Bunny explains what you discover, but you do the investigating.'}</p></div><div className="wood-shelf"><span>🌾</span><span>💧</span><span>🥣</span><span>🫙</span></div><div className="school-bunny-character"><div className="bunny-ears">◯ ◯</div><div className="bunny-head">• ᴥ •</div><div className="bunny-body">B</div></div>{!completed?<div className="learning-table"><div className="station-object">{s.icon}<small>INVESTIGATION TABLE</small></div><div className="discovery-buttons">{s.facts.map((f,i)=><button key={f} className={revealed.includes(i)?'discovered':''} onClick={()=>reveal(i)}><span>{revealed.includes(i)?'✓':'?'}</span>{revealed.includes(i)?f:'INSPECT CLUE'}</button>)}</div></div>:<div className="mission-crate"><span>🧺</span><b>STARTER KIT MISSION</b><small>{starterSupplies.length} ITEMS TO FIND AND BUY</small></div>}<div className="bunny-speech"><small>BUNNY SAYS</small><h2>{completed?'Ready for a real quest?':s.title}</h2><p>{completed?'We need ingredients and equipment before we can make a starter. Quest Meadow is where you earn your first coins. Then you decide which Bunnywood shop has each item.':ready?s.check:'Find all three clues on the investigation table.'}</p>{!completed&&ready&&<button onClick={next}>{station===2?'🏅 ACCEPT STARTER MISSION':'NEXT DISCOVERY →'}</button>}{completed&&<button onClick={onQuest}>🗺️ ENTER QUEST MEADOW →</button>}</div></div>{completed&&<div className="school-mission-board"><div><small>MISSION INVENTORY</small><h2>Your Starter Kit</h2><p>Tap an item for Bunny’s reminder. The list stays useful while you earn and shop.</p></div><div className="mission-supplies">{starterSupplies.map(x=><button key={x.id} onClick={()=>setOpenItem(openItem===x.id?null:x.id)} className={openItem===x.id?'open':''}><span>{x.emoji}</span><b>{x.name}</b><small>{openItem===x.id?x.teaching:`🪙 ${x.cost} · ${x.shop==='grocery'?'GROCERY':'SUPPLY SHOP'}`}</small></button>)}</div><button className="mission-launch" onClick={onQuest}>BEGIN THE LOST SUPPLY WAGON QUEST →</button></div>}</section>;
}
