import { useMemo, useState } from 'react';

type Props={day:number;mature:boolean;onAdvance:(mature:boolean)=>void;onBack:()=>void;onSchool:()=>void};
type Clue={label:string;value:string;detail:string};
type Scenario={name:string;mood:string;rise:number;bubbles:string;aroma:string;temp:number;hours:number;correct:string;options:string[];lesson:string};
const days:Scenario[]=[
 {name:'Day 1 · Just Mixed',mood:'sleepy',rise:0,bubbles:'Almost none',aroma:'Fresh flour',temp:72,hours:10,correct:'Observe and give it more time',options:['Feed it immediately','Observe and give it more time','Throw it away'],lesson:'A brand-new starter may look quiet. One check does not tell the whole story.'},
 {name:'Day 2 · First Activity',mood:'curious',rise:35,bubbles:'Many small bubbles',aroma:'Mild and grainy',temp:74,hours:22,correct:'Record the clues and continue the care routine',options:['Record the clues and continue the care routine','Add sugar to make more bubbles','Put it in the freezer'],lesson:'Early activity is exciting, but consistency over several cycles matters more than one burst.'},
 {name:'Day 3 · Quiet Again',mood:'worried',rise:8,bubbles:'A few bubbles',aroma:'Tangy',temp:69,hours:20,correct:'Keep caring for it and watch the trend',options:['Keep caring for it and watch the trend','Declare it dead','Add commercial yeast'],lesson:'Young starters often change pace. A quieter day can still be part of development.'},
 {name:'Day 4 · Getting Stronger',mood:'happy',rise:70,bubbles:'Bubbles throughout',aroma:'Tangy and yeasty',temp:73,hours:16,correct:'Mark the rise and complete the next feeding carefully',options:['Ignore the rise line','Mark the rise and complete the next feeding carefully','Add extra water until runny'],lesson:'Rise, bubbles, aroma, time, and temperature work together as evidence.'},
 {name:'Day 5 · Strong Cycle',mood:'excited',rise:105,bubbles:'Very active',aroma:'Pleasantly sour',temp:75,hours:12,correct:'Record a strong cycle and repeat it',options:['Record a strong cycle and repeat it','Stop feeding forever','Move it outside overnight'],lesson:'A strong rise is useful evidence, but maturity is shown by repeatable performance.'},
 {name:'Day 6 · Prove It',mood:'proud',rise:115,bubbles:'Very active from bottom to top',aroma:'Clean, tangy, yeasty',temp:74,hours:11,correct:'Confirm repeated strength and graduate',options:['Confirm repeated strength and graduate','Start over because it smells sour','Add candy to reward it'],lesson:'Repeated, predictable activity is the goal. Now the starter is ready for the next course.'},
];
const icons:Record<string,string>={sleepy:'😴',curious:'🙂',worried:'😐',happy:'😊',excited:'😄',proud:'🤩'};
export default function StarterCare({day,mature,onAdvance,onBack,onSchool}:Props){
 const index=Math.min(Math.max(day,0),days.length-1);const s=days[index];const[seen,setSeen]=useState<string[]>([]);const[hearts,setHearts]=useState(3);const[feedback,setFeedback]=useState('');const[ready,setReady]=useState(false);
 const clues:Clue[]=useMemo(()=>[
  {label:'Rise',value:`${s.rise}%`,detail:s.rise<15?'Almost no rise yet':s.rise<80?'Some visible rise':'Strong rise above the mark'},
  {label:'Bubbles',value:s.bubbles,detail:'Look through the clear jar, not only at the top.'},
  {label:'Aroma',value:s.aroma,detail:'Aroma is one clue and should be considered with the others.'},
  {label:'Temperature',value:`${s.temp}°F`,detail:'Temperature helps explain why fermentation may move faster or slower.'},
  {label:'Time',value:`${s.hours} hours`,detail:'Time since the last care step gives context to the other clues.'},
 ],[s]);
 function inspect(label:string){setSeen(v=>v.includes(label)?v:[...v,label]);if(seen.length>=3)setReady(true)}
 function decide(choice:string){if(!ready){setFeedback('Inspect at least four clues before deciding what your starter needs.');return}if(choice===s.correct){setFeedback(s.lesson);return}setHearts(h=>Math.max(0,h-1));setFeedback('That choice does not fit the evidence. Compare the rise, bubbles, aroma, temperature, and time again.')}
 const correct=feedback===s.lesson;
 return <section className="starter-pet"><header className="starter-pet-hud"><button onClick={onBack}>← BUNNYWOOD</button><div><small>STARTER COTTAGE · CARE ROOM</small><b>{mature?'MATURE STARTER':s.name}</b></div><span>❤️ {hearts}</span><span>📓 DAY {index+1}</span></header>
  <div className="starter-pet-room"><div className="pet-window"><span>☀️</span><i>72°</i></div><div className="pet-shelf"><span>🌾</span><span>💧</span><span>⚖️</span><span>🌡️</span></div><div className="pet-bunny">🐇</div><div className={`living-jar rise-${Math.min(5,Math.floor(s.rise/25))}`}><div className="jar-lid"/><div className="starter-fill"><i/><i/><i/><i/><i/><i/></div><div className="rise-mark">START</div><div className="starter-face">{icons[s.mood]}</div></div><div className="pet-dialogue"><small>BUNNY SAYS</small><h1>{mature?'Your starter is ready for bread school!':'Don’t guess. Read the starter.'}</h1><p>{mature?'You kept records and proved repeated strength. The next step begins back at the Schoolhouse.':'Inspect the jar like a baker. Open the clue cards, compare the evidence, then decide what your starter needs.'}</p></div></div>
  {!mature&&<div className="care-console"><div className="care-left"><small>STARTER CHECKUP</small><h2>Gather evidence first</h2><div className="clue-grid">{clues.map(c=><button key={c.label} className={seen.includes(c.label)?'seen':''} onClick={()=>inspect(c.label)}><b>{c.label}</b><strong>{seen.includes(c.label)?c.value:'?'}</strong><small>{seen.includes(c.label)?c.detail:'Tap to inspect'}</small></button>)}</div><div className="evidence-meter"><span style={{width:`${Math.min(100,(seen.length/4)*100)}%`}}/><b>{Math.min(seen.length,4)}/4 clues required</b></div></div><div className="care-right"><small>CARE DECISION</small><h2>What should Bunny do?</h2>{s.options.map(x=><button key={x} onClick={()=>decide(x)} disabled={hearts===0||correct}>{x}</button>)}{feedback&&<div className={`care-feedback ${correct?'good':'bad'}`}>{feedback}</div>}{correct&&<button className="advance-day" onClick={()=>onAdvance(index===days.length-1)}>{index===days.length-1?'🏅 CONFIRM STARTER MATURITY':'🌙 RECORD DAY & CONTINUE →'}</button>}{hearts===0&&<button className="retry-care" onClick={()=>{setHearts(3);setSeen([]);setReady(false);setFeedback('')}}>↻ REVIEW THE DAY AGAIN</button>}</div></div>}
  {mature&&<div className="starter-graduation"><span>🏅</span><div><small>STARTER APPRENTICE COMPLETE</small><h2>Your starter has become a dependable baking culture.</h2><p>The starter still needs ongoing care, but you have completed the first major Bunnywood chapter. Schoolhouse now begins the First Loaf course.</p><button onClick={onSchool}>🏫 GO TO SCHOOLHOUSE →</button></div></div>}
 </section>}
