import { useState } from 'react';

type Props={flourName:string;onMade:()=>void;onBack:()=>void};
export default function StarterKitchen({flourName,onMade,onBack}:Props){
 const steps=[
 {title:'Set up the station',instruction:`Put the clear jar, bowl, scale, ${flourName}, filtered water, spatula, thermometer, timer, and level marker on the worktable.`,task:'Tap the supplies in the order Bunny asks: scale → bowl → flour → water.',choices:['🌡️ Thermometer','⚖️ Scale','🥣 Bowl',`🌾 ${flourName}`,'💧 Filtered Water'],answers:[1,2,3,4]},
 {title:'Measure the flour',instruction:`Sourdough is measured by weight. Tare the bowl so its weight is not counted, then measure the ${flourName}.`,task:'Which scale reading shows 50 grams of flour after taring?',choices:['42 g','50 g','68 g'],answers:[1]},
 {title:'Measure the water',instruction:'Now measure the same weight of filtered water. Equal weights make this first mixture easy to understand.',task:'You have 50 g flour. How much filtered water should you measure?',choices:['25 g','50 g','100 g'],answers:[1]},
 {title:'Mix completely',instruction:'Combine the flour and water. Scrape the sides and make sure there are no pockets of dry flour.',task:'Choose the mixture that is ready for the jar.',choices:['Dry flour still visible','Evenly mixed thick paste','Watery layer on top'],answers:[1]},
 {title:'Mark and observe',instruction:'Move the mixture into the clear jar, clean the sides, mark its starting height, and check the room temperature.',task:'Why mark the starting height?',choices:['To decorate the jar','To see how much the starter rises','To keep the lid closed'],answers:[1]},
 {title:'Give it time',instruction:'Cover the jar appropriately and let the new culture begin. Our next job is observation—not constantly stirring it.',task:'What should we watch for as the starter develops?',choices:['Bubbles, rise, aroma, time and temperature','Only the clock','The color of the jar lid'],answers:[0]},
] as const;
 const[step,setStep]=useState(0);const[sub,setSub]=useState(0);const[feedback,setFeedback]=useState('');const s=steps[step];
 function pick(i:number){const expected=s.answers[Math.min(sub,s.answers.length-1)];if(i!==expected){setFeedback('That would cause a problem. Use what you learned at Starter School and try again.');return}setFeedback('Correct.');if(sub<s.answers.length-1){setSub(x=>x+1);return}if(step<steps.length-1){setTimeout(()=>{setStep(x=>x+1);setSub(0);setFeedback('')},350);return}onMade()}
 return <section className="starter-kitchen-game"><header><button onClick={onBack}>← BUNNYWOOD</button><div><small>STARTER COTTAGE · KITCHEN</small><b>MAKE YOUR FIRST STARTER · {flourName.toUpperCase()}</b></div><span>STEP {step+1}/{steps.length}</span></header><div className="kitchen-scene"><div className="window">☀️</div><div className="kitchen-shelves"><span>🫙</span><span>🥣</span><span>🌡️</span></div><div className="workbench"><span>⚖️</span><span>🌾</span><span>💧</span><span>🥄</span><span>🫙</span></div><div className="kitchen-bunny">🐇</div><div className="kitchen-speech"><small>BUNNY SAYS</small><h1>{s.title}</h1><p>{s.instruction}</p></div></div><div className="hands-on-task"><div className="task-progress">{steps.map((_,i)=><i key={i} className={i<step?'done':i===step?'current':''}/>)}</div><small>HANDS-ON CHALLENGE</small><h2>{s.task}</h2>{s.answers.length>1&&<p className="sequence-note">Station setup: {sub}/{s.answers.length} correct</p>}<div className="kitchen-choices">{s.choices.map((x,i)=><button key={x} onClick={()=>pick(i)}>{x}</button>)}</div>{feedback&&<strong className={feedback==='Correct.'?'correct':'wrong'}>{feedback}</strong>}</div></section>}
