import { useMemo, useState } from 'react';

type Scenario={prompt:string;choices:string[];answer:string;why:string};
const scenarios:Scenario[]=[
 {prompt:'Your starter rose 80% overnight, but the kitchen cooled by 8°F. Which pair of tools gives the best evidence about whether temperature slowed fermentation?',choices:['Thermometer + timer','Jar spatula + whisk','Scale + jar'],answer:'Thermometer + timer',why:'Temperature plus elapsed time lets you compare fermentation speed.'},
 {prompt:'You fed 60 g starter with 60 g flour and 60 g water. Which tool best checks whether you actually kept a 1:1:1 feeding ratio?',choices:['Gram scale','Thermometer','Timer'],answer:'Gram scale',why:'A ratio by mass has to be verified by weight.'},
 {prompt:'Two jars were fed at the same time. One doubled and one rose only 30%. Which setup gives the most useful comparison?',choices:['Mark both jar levels and compare time','Whisk both again','Move both to a brighter window'],answer:'Mark both jar levels and compare time',why:'Rise and time are the evidence you need before changing conditions.'},
 {prompt:'Bunny needs 150 g total feed at equal flour and water. Which measurement is correct?',choices:['75 g flour + 75 g water','100 g flour + 50 g water','50 g flour + 100 g water'],answer:'75 g flour + 75 g water',why:'Equal parts split 150 g into two 75 g portions.'},
 {prompt:'The starter smells sharper than yesterday but still rises well. What should Bunny check before assuming something is wrong?',choices:['Time since feeding and room temperature','Jar color only','Whether the spoon is metal'],answer:'Time since feeding and room temperature',why:'Aroma changes with fermentation stage and temperature.'},
 {prompt:'A recipe needs 240 g active starter. You already have 90 g. How much more active starter is needed?',choices:['150 g','130 g','170 g'],answer:'150 g',why:'240 − 90 = 150 g.'},
 {prompt:'Bunny wants the cleanest way to compare two feedings made on different days. Which record is most useful?',choices:['Feed weight + temperature + rise time','Jar shape + counter color','Only the final smell'],answer:'Feed weight + temperature + rise time',why:'Those three measurements let you compare conditions fairly.'},
 {prompt:'A starter reaches double height in 6 hours at 76°F and 9 hours at 70°F. What is the strongest conclusion?',choices:['The warmer condition fermented faster','The cooler condition used more flour','The jar at 76°F must be larger'],answer:'The warmer condition fermented faster',why:'The measured rise took less time under the warmer condition.'},
 {prompt:'You need to remove dried starter from the jar wall without changing the starter amount much. Best tool?',choices:['Jar spatula','Thermometer','Timer'],answer:'Jar spatula',why:'It scrapes the jar clean without adding or removing ingredients.'}
];
function shuffled<T>(a:T[]){return [...a].sort(()=>Math.random()-.5)}
export default function ToolTrail({onEarn,onExit}:{onEarn:(n:number)=>void;onExit:()=>void}){
 const[started,setStarted]=useState(false),[done,setDone]=useState(false),[claimed,setClaimed]=useState(false);const[round,setRound]=useState(0),[score,setScore]=useState(0),[lives,setLives]=useState(3);const[deck,setDeck]=useState<Scenario[]>(()=>shuffled(scenarios).slice(0,6));const[feedback,setFeedback]=useState('');
 const current=deck[Math.min(round,deck.length-1)];const reward=useMemo(()=>Math.max(3,Math.min(10,3+score)),[score]);
 function choose(choice:string){if(done)return;const good=choice===current.answer;if(good){setScore(s=>s+1);setFeedback(`Correct. ${current.why}`)}else{setLives(l=>Math.max(0,l-1));setFeedback(`Not quite. ${current.why}`)}const next=round+1;window.setTimeout(()=>{if(next>=deck.length||(!good&&lives<=1))setDone(true);else{setRound(next);setFeedback('')}},900)}
 function restart(){setStarted(false);setDone(false);setClaimed(false);setRound(0);setScore(0);setLives(3);setDeck(shuffled(scenarios).slice(0,6));setFeedback('')}
 return <section className="tool-trail">{!started&&!done?<div className="tool-start"><div className="tool-shed"><div className="shed-roof"/><div className="shed-door">TOOLS</div><div className="shed-tools">⚖️ 🌡️ 🫙 ⏲️</div></div><div className="tool-copy"><small>QUEST MEADOW REASONING GAME</small><h2>Tool Trail: Bakery Decisions</h2><p>These are not simple tool matches. Read each bakery situation, use the measurements and clues, and choose the best solution.</p><p>Six randomized scenarios. Three lives. Math, evidence, and sourdough reasoning all count.</p><button onClick={()=>setStarted(true)}>START TOOL TRAIL →</button></div></div>:started&&!done?<><div className="arcade-hud"><span>SCENARIO {round+1}/6</span><span>⭐ {score}</span><span>❤ {lives}</span></div><div className="tool-field"><div className="tool-clouds">☁️　　　　　☁️</div><div className="tool-hill"/><div className="tool-bunny">🐇</div><div className="rolling-tool"><span>🧠</span><b>BAKERY PROBLEM</b></div><div className="trail-split"><i/><i/><i/></div><p style={{maxWidth:760,margin:'0 auto 16px',fontWeight:800}}>{current.prompt}</p><div className="job-signs">{shuffled(current.choices).map((c,i)=><button key={c} onClick={()=>choose(c)} className={`job-sign j${i}`}><span>{i===0?'←':i===1?'↑':'→'}</span><b>{c}</b></button>)}</div>{feedback&&<div className="arcade-message">{feedback}</div>}</div></>:<div className="arcade-finish"><div className="finish-bunny">🐇</div><div><small>TOOL TRAIL COMPLETE</small><h2>{score===6?'Excellent reasoning!':score>=4?'Strong bakery thinking!':'Keep investigating!'}</h2><p>You solved <b>{score} of 6</b> evidence-and-measurement scenarios.</p><strong>Coin reward: 🪙 {reward}</strong>{!claimed?<button onClick={()=>{onEarn(reward);setClaimed(true)}}>COLLECT {reward} COINS</button>:<div className="finish-actions"><button onClick={restart}>NEW RANDOM RUN</button><button onClick={onExit}>BACK TO GAME TRAIL</button></div>}</div></div>}</section>
}
