import { useEffect, useState } from 'react';
import ChapterPath from './components/ChapterPath';
import BunnyGuide from './components/BunnyGuide';
import QuestMeadow from './components/QuestMeadow';
import Schoolhouse from './components/Schoolhouse';
import StarterKitchen from './components/StarterKitchen';
import StarterCare from './components/StarterCare';
import BreadSchool from './components/BreadSchool';
import { chapters, starterSupplies, type ChapterId, type ShopId } from './data/game';
type View='town'|'school'|'quest'|'grocery'|'supply'|'kitchen'|'starter'|'breadschool'|'recipe'|'bakery';
type Save={chapter:ChapterId;coins:number;owned:string[];starterSchool:boolean;starterMade:boolean;starterFeeds:number;starterMature:boolean;breadSchool:boolean};
const SAVE_KEY='sourdough-ing-it-v2';const initial:Save={chapter:'starter',coins:3,owned:[],starterSchool:false,starterMade:false,starterFeeds:0,starterMature:false,breadSchool:false};
function load():Save{try{const raw=localStorage.getItem(SAVE_KEY);return raw?{...initial,...JSON.parse(raw)}:initial}catch{return initial}}
export default function App(){const[game,setGame]=useState<Save>(load);const[view,setView]=useState<View>('town');useEffect(()=>localStorage.setItem(SAVE_KEY,JSON.stringify(game)),[game]);const nextSupply=starterSupplies.find(s=>!game.owned.includes(s.id));const allSupplies=!nextSupply;const currentChapter=chapters.find(c=>c.id===game.chapter)!;function earn(n:number){setGame(g=>({...g,coins:g.coins+n}))}function buy(id:string){const item=starterSupplies.find(s=>s.id===id);if(!item||game.owned.includes(id)||game.coins<item.cost)return;setGame(g=>({...g,coins:g.coins-item.cost,owned:[...g.owned,id]}))}function guarded(destination:View){if(!game.starterSchool&&['quest','grocery','supply','kitchen','starter'].includes(destination)){setView('school');return}setView(destination)}function Shop({kind}:{kind:ShopId}){const items=starterSupplies.filter(s=>s.shop===kind);return <section className={`town-shop ${kind}`}><BunnyGuide eyebrow={kind==='grocery'?'GROCERY STORE':'SUPPLY SHOP'} title={kind==='grocery'?'Starter ingredients':'Starter equipment'} text={kind==='grocery'?'Buy the food and water on your Starter School list.':'Buy the tools Bunny taught you about at Starter School.'} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/><div className="shop-room"><div className="shop-sign">{kind==='grocery'?'BUNNYWOOD GROCERY':'BUNNYWOOD SUPPLY CO.'}</div><div className="shop-grid">{items.map(item=>{const owned=game.owned.includes(item.id),can=game.coins>=item.cost;return <article key={item.id} className={owned?'owned':''}><span>{item.emoji}</span><h2>{item.name}</h2><p>{item.teaching}</p><b>{owned?'✓ OWNED':`🪙 ${item.cost}`}</b><button disabled={owned||!can} onClick={()=>buy(item.id)}>{owned?'IN YOUR KIT':can?'BUY ITEM':'EARN MORE COINS'}</button></article>})}</div></div><div className="kit-progress"><b>STARTER SETUP {game.owned.length}/{starterSupplies.length}</b><div>{starterSupplies.map(x=><span key={x.id} className={game.owned.includes(x.id)?'done':''}>{game.owned.includes(x.id)?'✓':x.emoji}</span>)}</div>{nextSupply&&<p>Next suggested item: <strong>{nextSupply.name}</strong> at the {nextSupply.shop==='grocery'?'Grocery Store':'Supply Shop'}.</p>}{allSupplies&&<button onClick={()=>setView('kitchen')}>🏡 TAKE THE KIT TO STARTER COTTAGE →</button>}</div></section>}
return <div className={`app-shell ${view==='town'?'town-mode':''} ${view==='quest'?'quest-mode':''} ${view==='school'||view==='breadschool'?'school-mode':''} ${view==='starter'?'starter-mode':''}`}><main className={['town','quest','school','breadschool','kitchen','starter'].includes(view)?'town-main':''}>
{view==='town'&&<section className="town-map town-master"><img src="./resources/bunnywood-town-master.png" alt="Bunnywood town"/><button className="map-hotspot starter-hotspot" aria-label="Enter Starter Cottage" onClick={()=>guarded(game.starterMade?'starter':'kitchen')}/><button className="map-hotspot bakery-hotspot" aria-label="Enter Bunnywood Bakery" onClick={()=>setView('bakery')}/><button className="map-hotspot kitchen-hotspot" aria-label="Enter Recipe Kitchen" onClick={()=>game.breadSchool?setView('recipe'):game.starterMature?setView('breadschool'):setView('town')}/><button className="map-hotspot grocery-hotspot" aria-label="Enter Grocery Store" onClick={()=>guarded('grocery')}/><button className="map-hotspot school-hotspot" aria-label="Enter Schoolhouse" onClick={()=>game.starterMature?setView('breadschool'):setView('school')}/><button className="map-hotspot quest-hotspot" aria-label="Enter Quest Meadow" onClick={()=>guarded('quest')}/><button className="map-hotspot track-hotspot" aria-label="Track my starter" onClick={()=>guarded('starter')}/></section>}
{view==='school'&&<Schoolhouse completed={game.starterSchool} onComplete={()=>setGame(g=>({...g,starterSchool:true}))} onBack={()=>setView('town')} onQuest={()=>setView('quest')}/>} 
{view==='breadschool'&&<BreadSchool completed={game.breadSchool} onComplete={()=>setGame(g=>({...g,breadSchool:true,chapter:'loaf'}))} onBack={()=>setView('town')} onKitchen={()=>setView('recipe')}/>} 
{view==='quest'&&<QuestMeadow coins={game.coins} goalName={nextSupply?.name} goalCost={nextSupply?.cost} onEarn={earn} onBack={()=>setView('town')} onGoStore={()=>setView(nextSupply?.shop==='supply'?'supply':'grocery')}/>} 
{view==='grocery'&&<Shop kind="grocery"/>}{view==='supply'&&<Shop kind="supply"/>}
{view==='kitchen'&&!allSupplies&&<section className="cottage-locked"><BunnyGuide eyebrow="STARTER COTTAGE · PREPARATION" title={`Starter Setup ${game.owned.length}/${starterSupplies.length}`} text={nextSupply?`We still need ${nextSupply.name}.`:'Finish the shopping list first.'} button="🗺️ EARN COINS →" onClick={()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
{view==='kitchen'&&allSupplies&&!game.starterMade&&<StarterKitchen onBack={()=>setView('town')} onMade={()=>{setGame(g=>({...g,starterMade:true,starterFeeds:0}));setView('starter')}}/>}{view==='kitchen'&&game.starterMade&&<StarterCare day={game.starterFeeds} mature={game.starterMature} onBack={()=>setView('town')} onSchool={()=>setView('breadschool')} onAdvance={(m)=>setGame(g=>({...g,starterFeeds:Math.min(5,g.starterFeeds+1),starterMature:m||g.starterMature}))}/>} 
{view==='starter'&&!game.starterMade&&<BunnyGuide eyebrow="STARTER COTTAGE" title="The jar is still empty." text="Complete Starter School and collect the starter kit first." button="GO TO QUEST MEADOW →" onClick={()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
{view==='starter'&&game.starterMade&&<StarterCare day={game.starterFeeds} mature={game.starterMature} onBack={()=>setView('town')} onSchool={()=>setView('breadschool')} onAdvance={(m)=>setGame(g=>({...g,starterFeeds:Math.min(5,g.starterFeeds+1),starterMature:m||g.starterMature}))}/>} 
{view==='recipe'&&<section className="recipe-coming"><BunnyGuide eyebrow="RECIPE KITCHEN · FIRST LOAF" title="The kitchen is unlocked." text="You passed First Loaf School. Next Bunny will turn the full bread process into a hands-on baking adventure: formula, mixing, folds, bulk fermentation, shaping, proofing, scoring, baking, and cooling." button="← BACK TO BUNNYWOOD" onClick={()=>setView('town')}/></section>}
{view==='bakery'&&<section className="bakery-stage"><BunnyGuide eyebrow={`${currentChapter.icon} ${currentChapter.title.toUpperCase()}`} title="The bakery comes later." text="First raise your starter and bake your first loaf." secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
</main></div>}
