import { useEffect, useMemo, useState } from 'react';
import ChapterPath from './components/ChapterPath';
import BunnyGuide from './components/BunnyGuide';
import QuestMeadow from './components/QuestMeadow';
import Schoolhouse from './components/Schoolhouse';
import { chapters, starterSupplies, type ChapterId } from './data/game';

type View='town'|'school'|'quest'|'store'|'kitchen'|'starter'|'loaf'|'bakery';
type Save={chapter:ChapterId;coins:number;owned:string[];starterSchool:boolean;starterMade:boolean;starterFeeds:number;starterMature:boolean};
const SAVE_KEY='sourdough-ing-it-v2';
const initial:Save={chapter:'starter',coins:3,owned:[],starterSchool:false,starterMade:false,starterFeeds:0,starterMature:false};
function load():Save{try{const raw=localStorage.getItem(SAVE_KEY);return raw?{...initial,...JSON.parse(raw)}:initial}catch{return initial}}
export default function App(){
 const[game,setGame]=useState<Save>(load);const[view,setView]=useState<View>('town');
 useEffect(()=>localStorage.setItem(SAVE_KEY,JSON.stringify(game)),[game]);
 const nextSupply=starterSupplies.find(s=>!game.owned.includes(s.id));const allSupplies=!nextSupply;const currentChapter=chapters.find(c=>c.id===game.chapter)!;
 const starterProgress=useMemo(()=>{let n=0;if(game.starterSchool)n++;if(allSupplies)n++;if(game.starterMade)n++;if(game.starterFeeds>=1)n++;if(game.starterMature)n++;return n},[allSupplies,game]);
 function earn(n:number){setGame(g=>({...g,coins:g.coins+n}))}
 function buyNext(){if(!game.starterSchool||!nextSupply||game.coins<nextSupply.cost)return;setGame(g=>({...g,coins:g.coins-nextSupply.cost,owned:[...g.owned,nextSupply.id]}))}
 function guarded(destination:View){if(!game.starterSchool&&['quest','store','kitchen','starter'].includes(destination)){setView('school');return}setView(destination)}
 return <div className={`app-shell ${view==='town'?'town-mode':''} ${view==='quest'?'quest-mode':''} ${view==='school'?'school-mode':''}`}>
  {view!=='town'&&view!=='quest'&&view!=='school'&&<header className="topbar"><div><span>🐇</span><div><b>SOURDOUGH-ING IT!</b><small>ADVENTURES WITH BUNNY</small></div></div><strong>🪙 {game.coins}</strong></header>}
  <main className={view==='town'||view==='quest'||view==='school'?'town-main':''}>
   {view!=='town'&&view!=='quest'&&view!=='school'&&<section className="adventure-header"><ChapterPath current={game.chapter}/><div className="chapter-title"><small>MAIN ADVENTURE</small><h1>{currentChapter.icon} {currentChapter.title}</h1><p>{currentChapter.summary}</p></div></section>}
   {view==='town'&&<section className="town-map town-master"><img src="./resources/bunnywood-town-master.png" alt="Bunnywood town"/><button className="map-hotspot starter-hotspot" aria-label="Enter Starter Cottage" onClick={()=>guarded('starter')}/><button className="map-hotspot bakery-hotspot" aria-label="Enter Bunnywood Bakery" onClick={()=>setView('bakery')}/><button className="map-hotspot kitchen-hotspot" aria-label="Enter Recipe Kitchen" onClick={()=>guarded('kitchen')}/><button className="map-hotspot grocery-hotspot" aria-label="Enter Grocery Store" onClick={()=>guarded('store')}/><button className="map-hotspot school-hotspot" aria-label="Enter Schoolhouse" onClick={()=>setView('school')}/><button className="map-hotspot quest-hotspot" aria-label="Enter Quest Meadow" onClick={()=>guarded('quest')}/><button className="map-hotspot track-hotspot" aria-label="Track my starter" onClick={()=>guarded('starter')}/><button className="map-hotspot recipes-hotspot" aria-label="Recipes" onClick={()=>guarded('kitchen')}/></section>}
   {view==='school'&&<Schoolhouse completed={game.starterSchool} onComplete={()=>setGame(g=>({...g,starterSchool:true}))} onBack={()=>setView('town')} onQuest={()=>setView('quest')}/>} 
   {view==='quest'&&<QuestMeadow coins={game.coins} goalName={nextSupply?.name} goalCost={nextSupply?.cost} onEarn={earn} onBack={()=>setView('town')} onGoStore={()=>setView('store')}/>} 
   {view==='store'&&nextSupply&&<><BunnyGuide eyebrow="SHOPPING MISSION" title={`Next: ${nextSupply.name}`} text={nextSupply.teaching} button={game.coins>=nextSupply.cost?`BUY FOR ${nextSupply.cost} COINS`:'EARN MORE COINS →'} onClick={game.coins>=nextSupply.cost?buyNext:()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/><section className="supply-shelf"><div className="big-item"><span>{nextSupply.emoji}</span><h2>{nextSupply.name}</h2><strong>🪙 {nextSupply.cost}</strong></div><div className="shopping-progress"><small>STARTER SHOPPING LIST</small>{starterSupplies.map(s=><span key={s.id} className={game.owned.includes(s.id)?'done':s.id===nextSupply.id?'current':''}>{game.owned.includes(s.id)?'✓':s.emoji} {s.name}</span>)}</div></section></>}
   {view==='store'&&!nextSupply&&<BunnyGuide eyebrow="SHOPPING COMPLETE" title="We have everything!" text="Now take everything to Starter Cottage. The kitchen is where we make our starter." button="🏡 GO TO STARTER COTTAGE →" onClick={()=>setView('kitchen')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
   {view==='kitchen'&&!allSupplies&&<BunnyGuide eyebrow="STARTER COTTAGE · LOCKED" title="We aren't ready to mix yet." text={`We still need ${nextSupply?.name}. Earn the coins and finish the shopping list first.`} button="🗺️ GO EARN COINS →" onClick={()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
   {view==='kitchen'&&allSupplies&&<section className="room-card kitchen-room"><div className="room-scene">☀️　🥣　⚖️　🌀<span>🐇</span></div><BunnyGuide eyebrow="STARTER COTTAGE · KITCHEN" title={game.starterMade?'Our starter is already made.':'Everything is ready. Let’s make our starter.'} text={game.starterMade?'Now our job is to care for it like a little kitchen pet.':'Use what you learned at school: weigh the brown rice flour and filtered water, mix, scrape the jar, mark the starting height, and cover it properly.'} button={game.starterMade?'CHECK MY STARTER →':'MAKE THE STARTER →'} onClick={()=>{if(!game.starterMade)setGame(g=>({...g,starterMade:true}));setView('starter')}} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
   {view==='starter'&&!game.starterMade&&<BunnyGuide eyebrow="STARTER COTTAGE" title="The jar is still empty." text="Finish Starter School, collect every supply, then come into the kitchen to make your starter." button="GO TO KITCHEN →" onClick={()=>setView('kitchen')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
   {view==='starter'&&game.starterMade&&<section className="starter-room"><div className="pet-scene"><span>🐇</span><div className="starter-jar">🫙<i>{game.starterMature?'🫧🫧🫧':game.starterFeeds?'🫧🫧':'·'}</i></div></div><BunnyGuide eyebrow={`STARTER CARE · ${starterProgress}/5`} title={game.starterMature?'Your starter is mature!':game.starterFeeds===0?'Let it rest before the first feeding.':'Keep feeding and watching the clues.'} text={game.starterMature?'We did it. Our starter is strong enough to move into the bread chapter.':'Watch bubbles, rise, smell, temperature, and time. Real sourdough is learned by observing the starter, not by blindly following a clock.'} button={game.starterMature?'🥖 UNLOCK FIRST LOAF →':'🥣 COMPLETE A CARE CYCLE'} onClick={()=>{if(game.starterMature){setGame(g=>({...g,chapter:'loaf'}));setView('town');return}setGame(g=>{const feeds=g.starterFeeds+1;return{...g,starterFeeds:feeds,starterMature:feeds>=4}})}} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
   {view==='loaf'&&<section className="loaf-school"><BunnyGuide eyebrow="CHAPTER 2 · FIRST LOAF" title="Starter becomes bread." text="Before baking, the next Schoolhouse course will teach the bread process." button="BACK TO TOWN →" onClick={()=>setView('town')}/></section>}
   {view==='bakery'&&<section className="bakery-stage"><BunnyGuide eyebrow={`${currentChapter.icon} ${currentChapter.title.toUpperCase()}`} title="The bakery comes later." text="First raise your starter and learn to bake. Bunnywood Bakery will unlock as your skills grow." secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
  </main>
 </div>
}
