import { useEffect, useMemo, useState } from 'react';
import ChapterPath from './components/ChapterPath';
import BunnyGuide from './components/BunnyGuide';
import QuestMeadow from './components/QuestMeadow';
import Schoolhouse from './components/Schoolhouse';
import StarterKitchen from './components/StarterKitchen';
import { chapters, starterSupplies, type ChapterId, type ShopId } from './data/game';
type View='town'|'school'|'quest'|'grocery'|'supply'|'kitchen'|'starter'|'loaf'|'bakery';
type Save={chapter:ChapterId;coins:number;owned:string[];starterSchool:boolean;starterMade:boolean;starterFeeds:number;starterMature:boolean};
const SAVE_KEY='sourdough-ing-it-v2';const initial:Save={chapter:'starter',coins:3,owned:[],starterSchool:false,starterMade:false,starterFeeds:0,starterMature:false};
function load():Save{try{const raw=localStorage.getItem(SAVE_KEY);return raw?{...initial,...JSON.parse(raw)}:initial}catch{return initial}}
export default function App(){const[game,setGame]=useState<Save>(load);const[view,setView]=useState<View>('town');useEffect(()=>localStorage.setItem(SAVE_KEY,JSON.stringify(game)),[game]);const nextSupply=starterSupplies.find(s=>!game.owned.includes(s.id));const allSupplies=!nextSupply;const currentChapter=chapters.find(c=>c.id===game.chapter)!;const starterProgress=useMemo(()=>{let n=0;if(game.starterSchool)n++;if(allSupplies)n++;if(game.starterMade)n++;if(game.starterFeeds>=1)n++;if(game.starterMature)n++;return n},[allSupplies,game]);function earn(n:number){setGame(g=>({...g,coins:g.coins+n}))}function buy(id:string){const item=starterSupplies.find(s=>s.id===id);if(!item||game.owned.includes(id)||game.coins<item.cost)return;setGame(g=>({...g,coins:g.coins-item.cost,owned:[...g.owned,id]}))}function guarded(destination:View){if(!game.starterSchool&&['quest','grocery','supply','kitchen','starter'].includes(destination)){setView('school');return}setView(destination)}function Shop({kind}:{kind:ShopId}){const items=starterSupplies.filter(s=>s.shop===kind);const name=kind==='grocery'?'GROCERY STORE':'SUPPLY SHOP';return <section className={`town-shop ${kind}`}><BunnyGuide eyebrow={name} title={kind==='grocery'?'Starter ingredients':'Starter equipment'} text={kind==='grocery'?'Buy the food and water on your Starter School list.':'Buy the tools Bunny taught you about at Starter School.'} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/><div className="shop-room"><div className="shop-sign">{kind==='grocery'?'BUNNYWOOD GROCERY':'BUNNYWOOD SUPPLY CO.'}</div><div className="shop-grid">{items.map(item=>{const owned=game.owned.includes(item.id);const can=game.coins>=item.cost;return <article key={item.id} className={owned?'owned':''}><span>{item.emoji}</span><h2>{item.name}</h2><p>{item.teaching}</p><b>{owned?'✓ OWNED':`🪙 ${item.cost}`}</b><button disabled={owned||!can} onClick={()=>buy(item.id)}>{owned?'IN YOUR KIT':can?'BUY ITEM':'EARN MORE COINS'}</button></article>})}</div></div><div className="kit-progress"><b>STARTER SETUP {game.owned.length}/{starterSupplies.length}</b><div>{starterSupplies.map(x=><span key={x.id} className={game.owned.includes(x.id)?'done':''}>{game.owned.includes(x.id)?'✓':x.emoji}</span>)}</div>{nextSupply&&<p>Next suggested item: <strong>{nextSupply.name}</strong> at the {nextSupply.shop==='grocery'?'Grocery Store':'Supply Shop'}.</p>}{allSupplies&&<button onClick={()=>setView('kitchen')}>🏡 TAKE THE KIT TO STARTER COTTAGE →</button>}</div></section>}
return <div className={`app-shell ${view==='town'?'town-mode':''} ${view==='quest'?'quest-mode':''} ${view==='school'?'school-mode':''}`}>
{view!=='town'&&view!=='quest'&&view!=='school'&&view!=='kitchen'&&<header className="topbar"><div><span>🐇</span><div><b>SOURDOUGH-ING IT!</b><small>ADVENTURES WITH BUNNY</small></div></div><strong>🪙 {game.coins}</strong></header>}<main className={['town','quest','school','kitchen'].includes(view)?'town-main':''}>
{!['town','quest','school','kitchen'].includes(view)&&<section className="adventure-header"><ChapterPath current={game.chapter}/><div className="chapter-title"><small>MAIN ADVENTURE</small><h1>{currentChapter.icon} {currentChapter.title}</h1><p>{currentChapter.summary}</p></div></section>}
{view==='town'&&<section className="town-map town-master"><img src="./resources/bunnywood-town-master.png" alt="Bunnywood town"/><button className="map-hotspot starter-hotspot" aria-label="Enter Starter Cottage" onClick={()=>guarded(game.starterMade?'starter':'kitchen')}/><button className="map-hotspot bakery-hotspot" aria-label="Enter Bunnywood Bakery" onClick={()=>setView('bakery')}/><button className="map-hotspot kitchen-hotspot" aria-label="Enter Recipe Kitchen" onClick={()=>setView('town')}/><button className="map-hotspot grocery-hotspot" aria-label="Enter Grocery Store" onClick={()=>guarded('grocery')}/><button className="map-hotspot school-hotspot" aria-label="Enter Schoolhouse" onClick={()=>setView('school')}/><button className="map-hotspot quest-hotspot" aria-label="Enter Quest Meadow" onClick={()=>guarded('quest')}/><button className="map-hotspot track-hotspot" aria-label="Track my starter" onClick={()=>guarded('starter')}/></section>}
{view==='school'&&<Schoolhouse completed={game.starterSchool} onComplete={()=>setGame(g=>({...g,starterSchool:true}))} onBack={()=>setView('town')} onQuest={()=>setView('quest')}/>} 
{view==='quest'&&<QuestMeadow coins={game.coins} goalName={nextSupply?.name} goalCost={nextSupply?.cost} onEarn={earn} onBack={()=>setView('town')} onGoStore={()=>setView(nextSupply?.shop==='supply'?'supply':'grocery')}/>} 
{view==='grocery'&&<Shop kind="grocery"/>}{view==='supply'&&<Shop kind="supply"/>}
{view==='kitchen'&&!allSupplies&&<section className="cottage-locked"><div className="locked-cottage-art">🏡<span>🐇</span></div><BunnyGuide eyebrow="STARTER COTTAGE · PREPARATION" title={`Starter Setup ${game.owned.length}/${starterSupplies.length}`} text={nextSupply?`The kitchen is ready, but our starter kit is not. We still need ${nextSupply.name} from the ${nextSupply.shop==='grocery'?'Grocery Store':'Supply Shop'}.`:'Finish the shopping list first.'} button="🗺️ EARN COINS IN QUEST MEADOW →" onClick={()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
{view==='kitchen'&&allSupplies&&!game.starterMade&&<StarterKitchen onBack={()=>setView('town')} onMade={()=>{setGame(g=>({...g,starterMade:true}));setView('starter')}}/>}{view==='kitchen'&&game.starterMade&&<BunnyGuide eyebrow="STARTER COTTAGE" title="Your starter lives here now." text="Let's check on it." button="CHECK MY STARTER →" onClick={()=>setView('starter')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
{view==='starter'&&!game.starterMade&&<BunnyGuide eyebrow="STARTER COTTAGE" title="The jar is still empty." text="Complete Starter School and the shopping list before making the starter." button="GO TO QUEST MEADOW →" onClick={()=>setView('quest')} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/>} 
{view==='starter'&&game.starterMade&&<section className="starter-room"><div className="pet-scene"><span>🐇</span><div className="starter-jar">🫙<i>{game.starterMature?'🫧🫧🫧':game.starterFeeds?'🫧🫧':'·'}</i></div></div><BunnyGuide eyebrow={`STARTER CARE · ${starterProgress}/5`} title={game.starterMature?'Your starter is mature!':game.starterFeeds===0?'Day One: observe first.':'Keep feeding and watching the clues.'} text={game.starterMature?'Your starter has demonstrated repeated activity. The next Schoolhouse course will prepare us for bread.':'Bubbles, rise, aroma, time and temperature tell the story. The next build will turn starter care into its own observation-and-feeding system.'} button={game.starterMature?'🏫 BEGIN FIRST LOAF SCHOOL →':'🥣 COMPLETE A CARE CYCLE'} onClick={()=>{if(game.starterMature){setGame(g=>({...g,chapter:'loaf'}));setView('school');return}setGame(g=>{const feeds=g.starterFeeds+1;return{...g,starterFeeds:feeds,starterMature:feeds>=4}})}} secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
{view==='loaf'&&<section className="loaf-school"><BunnyGuide eyebrow="CHAPTER 2 · FIRST LOAF" title="Starter becomes bread." text="The next Schoolhouse course will teach the bread process before Bunny lets us bake." button="BACK TO TOWN →" onClick={()=>setView('town')}/></section>}{view==='bakery'&&<section className="bakery-stage"><BunnyGuide eyebrow={`${currentChapter.icon} ${currentChapter.title.toUpperCase()}`} title="The bakery comes later." text="First raise your starter and learn to bake." secondary="← BACK TO TOWN" onSecondary={()=>setView('town')}/></section>}
</main></div>}
